### ISSUE TITLE
[ENH]: Use null-safe dependencies

### ISSUE THREAD

**Issue by robert-virkus** [Canardoux/tau#639]
**Is your feature request related to a problem? Please describe.**
Both `flutter_sound` and `flutter_sound_lite` depend on older dependencies, thus projects that depend on `fluter_sound` or `flutter_sound_light` cannot be upgraded to null-safe code.

**Describe the solution you'd like**
Upgrade dependencies, e.g.:
```yaml
dependencies:
  flutter_spinkit: ^5.0.0
  logger: ^1.0.0-nullsafety.0
  path: ^1.8.0
  path_provider: ^2.0.1
  provider: ^5.0.0
  recase: ^3.0.1
  synchronized: ^3.0.0
  uuid: ^3.0.1
```

**Describe alternatives you've considered**
sorry, none

**Additional context**
Note that you can mix null-safe and other code now, compare
https://dart.dev/null-safety/migration-guide
